**Numpy**

In [1]:
import numpy as np #pip install numpy

In [2]:
np.__version__

'2.2.6'

In [3]:
import sys
sys.version

'3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]'

Creating LIST

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

Converting List to array

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(my_list)

list

arange() with one argument

In [9]:
np.arange(10) #Arrange values 0 to 9 total 10 values in array format     

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5.0) #Arrange values 0. to 4. total 5 values in array format

array([0., 1., 2., 3., 4.])

arange() with two argument

In [11]:
np.arange(0,5) 

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20)# act like range()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20,10) #1st arg < 2nd arg

array([], dtype=int64)

In [14]:
np.arange(-20,10) #It starts from -20 and ends with 10-1. (ie.9)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-20,-10) #-20 to -11

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

arange() with three argument

In [16]:
np.arange(10,30,5) # starting from 10, end point 30, and steps 5

array([10, 15, 20, 25])

In [17]:
np.arange() #error arange() requires atlist one argument

TypeError: arange() requires stop to be specified.

zeros()

In [18]:
np.zeros(5) #gives float :- Parameter tunning = System given parameter is called Parameter tunning

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros(5,dtype=int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [20]:
np.zeros((2,2),dtype=int) #2d

array([[0, 0],
       [0, 0]])

In [21]:
np.zeros((2,10)) #2-rows (ie.0 to 1) and 10-column (ie.0 to 9)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

ones()

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

random.rand()

In [26]:
np.rand(4) #error

AttributeError: module 'numpy' has no attribute 'rand'

In [27]:
np.random.rand(4)

array([0.06043304, 0.11971294, 0.20996184, 0.70187817])

In [28]:
np.random.rand(4) #Every time diffrent numbers

array([0.31139166, 0.80614998, 0.17120044, 0.18978949])

In [29]:
np.random.rand(2,2) #2x2 matrix by random numbers.

array([[0.18255507, 0.49873554],
       [0.08477439, 0.6749291 ]])

random.randint()

In [30]:
np.random.randint(2,8) #Generate random int number 2 to 8-1 (ie.7)

4

In [31]:
np.random.randint(2,8) #Generate random int number 2 to 8-1 (ie.7)

5

In [32]:
np.random.randint(2,8,4) #Generate 4 random int number 2 to 8-1 (ie.7)

array([7, 2, 5, 7], dtype=int32)

In [33]:
np.random.randint(2,8,4) #Generate 4 random int number 2 to 8-1 (ie.7)

array([2, 7, 5, 3], dtype=int32)

Only 0 using random.randint()

In [34]:
np.random.randint(0,1) #Every time it returns 0

0