In [2]:
import numpy as np

In [3]:
np.arange(1,13) #array from 1 to 16-1 ie.15

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

reshape()

In [4]:
np.arange(1,13).reshape(3,4) #reshape() reshape the array by 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
np.arange(1,7).reshape(3,2) #reshape() reshape the array by 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(1,7).reshape(4,5) #error 4*5 != 6

ValueError: cannot reshape array of size 6 into shape (4,5)

In [7]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

Slicing in matrix

In [8]:
b=np.random.randint(10,20,(5,4)) #random int between 10 to 20-1 with 5 rows and 4 columns
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [9]:
type(b)

numpy.ndarray

In [10]:
b[:] #all values of matrix

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [11]:
b[1:3] #values of row number 1 and 3-1 ie 2

array([[11, 13, 12, 11],
       [17, 16, 15, 11]], dtype=int32)

[:] It will print rows 

[,] It will print specific value of matrix

In [12]:
b[1,3] #Specific value of the matrix

np.int32(11)

In [13]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [14]:
b[1,2] # value from row 1 and column 2

np.int32(12)

In [15]:
b[1,3] # value from row 1 and column 3

np.int32(11)

In [16]:
b[1,4] # error,In matrix only 0 to 3 columns not 0 to 4

IndexError: index 4 is out of bounds for axis 1 with size 4

In [17]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [18]:
b[1,-1] # row no 1 and column -1 

np.int32(11)

In [19]:
b[3,-2] # row no 3 and column -2 

np.int32(18)

In [20]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [21]:
b[2:3] #values of row number 2 and 3-1 ie 2 (ie. it returns only one row)

array([[17, 16, 15, 11]], dtype=int32)

In [22]:
b[0:-2] #values of row number 0 and -2 ie -2-1 ie -3

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11]], dtype=int32)

In [23]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [24]:
b[-5:3] #values of row number -5 and 3 ie 3-1 ie 2

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11]], dtype=int32)

In [25]:
b[-5,3] # value from row -5 and column 3

np.int32(13)

In [26]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [27]:
b[-5,-3]

np.int32(18)

Operations

In [28]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [29]:
b[::-1] #print in backward (reversed) order

array([[17, 15, 14, 18],
       [13, 10, 18, 17],
       [17, 16, 15, 11],
       [11, 13, 12, 11],
       [18, 18, 18, 13]], dtype=int32)

In [30]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [31]:
b[::-2] #print in backward (reversed) order with 2 steps

array([[17, 15, 14, 18],
       [17, 16, 15, 11],
       [18, 18, 18, 13]], dtype=int32)

In [32]:
b[::-3] #print in backward (reversed) order with 3 steps

array([[17, 15, 14, 18],
       [11, 13, 12, 11]], dtype=int32)

In [33]:
b

array([[18, 18, 18, 13],
       [11, 13, 12, 11],
       [17, 16, 15, 11],
       [13, 10, 18, 17],
       [17, 15, 14, 18]], dtype=int32)

In [34]:
b[:10:3] #prints between 0 to 10 with 3 steps

array([[18, 18, 18, 13],
       [13, 10, 18, 17]], dtype=int32)

Functions

In [35]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [36]:
arr.max() # finds the maximum number from array

np.int64(9)

In [37]:
arr.min() # Finds the minimum number from array

np.int64(0)

In [38]:
arr.mean() #returns average numbers of array ie. (0+1+2+3+4+5+6+7+8+9)/10

np.float64(4.5)

median()

In [39]:
median(arr) #error

NameError: name 'median' is not defined

In [40]:
from numpy import * #All 256 functions of numpy called internally
a=array([1,2,3,4,9])
median(a) #returns median

np.float64(3.0)

Indexing

In [41]:
matri=np.arange(0,100).reshape(10,10)
matri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [42]:
row=4
colum=5

In [43]:
row

4

In [44]:
colum

5

In [45]:
matri[row:colum] #it like matri[4:5] ie.values of row number 4 and 5-1 ie 4 (ie. it returns only one row)

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
matri[row,colum] 

np.int64(45)

In [47]:
matri[7] #by default it represent row

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [48]:
matri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
matri[:,6] #get values by column .  [:,number]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [50]:
matri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
matri[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [52]:
matri[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
matri[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [54]:
matri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
matri[2:6,2:4] #returns values of between row number 2 to 6-1 ie 5 and column number 2 to 4-1 ie 3

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [56]:
matri[1:2,2:4] #returns values of between row number 2 to 6-1 ie 5 and column number 2 to 4-1 ie 3

array([[12, 13]])

Masking in numpy (Filter)

In [57]:
matri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
id(matri)

2572264400880

In [ ]:
matri > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [63]:
matri[matri > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
matri[matri == 50]

array([50])

In [65]:
matri[matri != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Identity matrix

In [79]:
f=np.eye(4)
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Mathematical Functions

In [110]:
#Add two arraya

g=np.array([1,2,3,4])

added = np.add(g,2) #Add 2 to each element
print("Added 2 to g :",added)

Added 2 to g : [3 4 5 6]


In [111]:
#Square of each element
square = np.power(g,2) ##Square each element
print("Squared g :",square)

Squared g : [ 1  4  9 16]


In [112]:
#Square root of each element
sqrt_val = np.sqrt(g) #Square root of each element
print("Square root  of  g:",sqrt_val)

Square root  of  g: [1.         1.41421356 1.73205081 2.        ]


In [114]:
# Dot product of two arrays
# a2 = np.array([1,2,3])
# np.dot(a2, g)
# # np.dot(a2, g) # Dot product of a2 and g  #Error

Statistical Functions

In [117]:
s=np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s : ",mean)

Mean of s :  2.5


In [120]:
#Standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s : ",std_dev)

Standard deviation of s :  1.118033988749895


In [123]:
# Minimum element of an array
minimum = np.min(s)
minimum

np.int64(1)

In [126]:
# Maximum element of an array
maximum = np.max(s)
maximum

np.int64(4)